## degrees of freedom

<dfn>The number of observations that are free to vary to produce a known outcome.</dfn>

If you run 5 people and ask them their age, and you know the mean age of those 5 people is 20.1, then four of those people can have any age, but the 5th person must have a specific age to maintain the mean of 20.1. The mean age here is the known outcome and four people's age can vary freely, so the *degrees of freedom* is 4.

You need to know the degrees of freedom (usually abbreviated *df*) to interpret test statistics like t-values and F-values.

```{r, echo = FALSE, out.width = "75%", fig.cap = "How p-values vary depending on the degrees of freedom for specific t-values in a t-test."}
dat <- crossing(
  t = seq(1.8, 2.6, .2),
  df = 1:100
) %>%
mutate(p = purrr::map2_dbl(t, df, pt, lower.tail = FALSE) * 2)

ggplot(dat, aes(x = df, y = p, color = as.factor(t))) +
  geom_line(size = 1) +
  scale_color_brewer(name = "t-value", palette = "Dark2") +
  scale_x_continuous(name = "degrees of freedom (df)") +
  scale_y_continuous(name = "p-value (two-tailed)")

```

<dfn>TRANSLATED TERM:自由度  有n個觀察值且已知樣本平均值，不能用已知估計值推測的可變異觀察值個數。</dfn>

假設你想知道五位同班同學今年幾歲，而你事先知道五人平均20.1歲。樣本平均值是已知的估計值，你只能推測其中一位的真實年齡是20.1歲，但是其他四位回答的年齡可以是任何數值。這個例子的樣本有4個觀察值可自由變異，所以**自由度**是4。

當你進行統計檢定如t檢定和F檢定，必須要知道正確的自由度(簡寫 *df*)。

中文參考資料：林澤民(2017)。[統計學中算變異量為什麼要除以n-1？什麼是「自由度」？](http://blog.udn.com/nilnimest/92412101)
