## sample

<dfn>A subset of the [population](p.html#population) that you wish to make an inference about through your test.</dfn>

The sample is a smaller group obtained from your population but it is key that the sample is representative of the population.

As in most instances it is realistically impossible to test all members of a population, a sample is derived, that represents the population of interest, from the population. The sample should have the same demographic characteristics as the population for example. If your sample is not representative of the population then any conclusions derived from your test are invalid.

```{block type="info"}
If the population is small enough to feasibly test in full, e.g. all students in a final year Psychology class, then your sample and the population are the same.
```

For an interesting paper on populations, samples and generalisability, see:

* Simons, D. J., Shoda, Y., & Lindsay, D. S. (2017). Constraints on Generality (COG): A Proposed Addition to All Empirical Papers. Perspectives on Psychological Science, 12(6), 1123–1128. {doi: 10.1177/1745691617708630}(https://doi.org/10.1177/1745691617708630){target="_blank"}}
